name: Docker Build and Terraform Deploy Pipeline

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE: vasudhajha/simple-time-service

jobs:
  docker_build_and_push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Read Version from VERSION file
        id: read_version
        run: |
            cd app 
            echo "IMAGE_TAG=$(cat VERSION)" >> $GITHUB_ENV

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          cd app
          docker build -t $DOCKER_IMAGE:$IMAGE_TAG .

      - name: Push Docker Image to DockerHub
        run: docker push $DOCKER_IMAGE:$IMAGE_TAG

#   terraform_deploy_infrastructure:
#     name: Deploy Infrastructure with Terraform
#     runs-on: ubuntu-latest
#     needs: docker_build_and_push

#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v4

#       - name: Read Version from VERSION file
#         id: read_version
#         run: |
#             cd app
#             echo "IMAGE_TAG=$(cat VERSION)" >> $GITHUB_ENV

#       - name: Set Up Terraform
#         uses: hashicorp/setup-terraform@v3

#       - name: Terraform Init and Apply
#         working-directory: terraform
#         env:
#           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         run: |
#           terraform init
#           terraform apply -auto-approve -var="container_image=$DOCKER_IMAGE:$IMAGE_TAG"
